version: '3'
services:
  spring-boot-app:
    image: openjdk:21
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    volumes:
      - ./target:/app
    working_dir: /app
    command: ["java", "-jar", "SpringBootTodoVinko-0.0.1-SNAPSHOT.jar"]
    depends_on:
      - h2-db

  h2-db:
    image: h2database/h2:latest
    container_name: h2-db
    ports:
      - "8082:8082"